export * from './auth.service';
import { AuthService } from './auth.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './event.service';
import { EventService } from './event.service';
export * from './person.service';
import { PersonService } from './person.service';
export * from './place.service';
import { PlaceService } from './place.service';
export * from './relationship.service';
import { RelationshipService } from './relationship.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './share.service';
import { ShareService } from './share.service';
export * from './thing.service';
import { ThingService } from './thing.service';
export const APIS = [AuthService, DocumentService, EventService, PersonService, PlaceService, RelationshipService, SearchService, ShareService, ThingService];
