/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResultType } from './resultType';


/**
 * Advanced search request with filtering and pagination
 */
export interface AdvancedSearchRequest { 
    /**
     * Search query text
     */
    query?: string | null;
    /**
     * Filter by entity types
     */
    entityTypes?: Array<ResultType> | null;
    /**
     * Start date for filtering (if applicable)
     */
    startDate?: string | null;
    /**
     * End date for filtering (if applicable)
     */
    endDate?: string | null;
    /**
     * Page number (0-indexed)
     */
    page?: number | null;
    /**
     * Results per page
     */
    pageSize?: number | null;
    /**
     * Maximum results to fetch before pagination
     */
    maxResults?: number | null;
    /**
     * Include faceted counts in results
     */
    includeFacets?: boolean;
}

