/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonCreateDto } from './personCreateDto';


/**
 * Bulk person creation request
 */
export interface BulkPersonRequest { 
    people?: Array<PersonCreateDto> | null;
}

