/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Bulk operation result
 */
export interface BulkOperationResult { 
    successCount?: number;
    failureCount?: number;
    createdIds?: Array<string> | null;
    errors?: Array<string> | null;
}

