/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of data change
 */
export const ChangeType = {
    Created: 'Created',
    Updated: 'Updated',
    Deleted: 'Deleted',
    Merged: 'Merged',
    Imported: 'Imported'
} as const;
export type ChangeType = typeof ChangeType[keyof typeof ChangeType];

