/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';


/**
 * Denormalized table for querying citations by source
 */
export interface CitationBySource { 
    userId?: string;
    title?: string | null;
    citationId?: string;
    entityId?: string;
    entityType?: EntityType;
    fieldName?: string | null;
    qualityRating?: number;
    createdAt?: string;
}
export namespace CitationBySource {
}


