/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictResolutionStrategy } from './conflictResolutionStrategy';
import { PrivacyLevel } from './privacyLevel';


/**
 * Conflicting information entry
 */
export interface ConflictingInformation { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    /**
     * User who owns this conflict record (overrides base to add partition key)
     */
    userId?: string;
    entityId?: string;
    fieldName?: string | null;
    /**
     * First value/claim
     */
    value1?: string | null;
    /**
     * Second value/claim
     */
    value2?: string | null;
    /**
     * Citation for first value
     */
    citation1Id?: string | null;
    /**
     * Citation for second value
     */
    citation2Id?: string | null;
    resolution?: ConflictResolutionStrategy;
    /**
     * Preferred value (if resolved)
     */
    preferredValue?: string | null;
    /**
     * Resolution notes
     */
    notes?: string | null;
    /**
     * When this was resolved
     */
    resolvedAt?: string | null;
}
export namespace ConflictingInformation {
}


