/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Conflict resolution strategy
 */
export const ConflictResolution = {
    KeepLocal: 'KeepLocal',
    KeepRemote: 'KeepRemote',
    KeepBoth: 'KeepBoth',
    Merge: 'Merge',
    Manual: 'Manual'
} as const;
export type ConflictResolution = typeof ConflictResolution[keyof typeof ConflictResolution];

