/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Strategy for resolving conflicting information
 */
export const ConflictResolutionStrategy = {
    Unresolved: 'Unresolved',
    PreferNewer: 'PreferNewer',
    PreferOlder: 'PreferOlder',
    PreferHigherQuality: 'PreferHigherQuality',
    ManualSelection: 'ManualSelection',
    KeepBoth: 'KeepBoth',
    Average: 'Average'
} as const;
export type ConflictResolutionStrategy = typeof ConflictResolutionStrategy[keyof typeof ConflictResolutionStrategy];

