/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { SharePermission } from './sharePermission';


/**
 * DTO for creating a share invitation
 */
export interface CreateShareInvitationDto { 
    toUserId?: string;
    entityType?: EntityType;
    entityId?: string;
    permission?: SharePermission;
    message?: string | null;
    expiresAt?: string | null;
}
export namespace CreateShareInvitationDto {
}


