/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictResolution } from './conflictResolution';


/**
 * Conflict when merging shared data
 */
export interface DataConflict { 
    userId?: string;
    entityId?: string;
    fieldName?: string | null;
    /**
     * Current value in user\'s data
     */
    localValue?: string | null;
    /**
     * Incoming value from shared source
     */
    remoteValue?: string | null;
    /**
     * User who owns the remote data
     */
    remoteUserId?: string;
    resolution?: ConflictResolution;
    /**
     * When the conflict was detected
     */
    detectedAt?: string;
    /**
     * When the conflict was resolved
     */
    resolvedAt?: string | null;
}
export namespace DataConflict {
}


