/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangeType } from './changeType';


/**
 * Tracks data provenance - who created/modified what
 */
export interface DataProvenance { 
    entityId?: string;
    changedAt?: string;
    /**
     * User who made the change
     */
    changedBy?: string;
    changeType?: ChangeType;
    /**
     * Field that was changed
     */
    fieldName?: string | null;
    /**
     * Old value (JSON)
     */
    oldValue?: string | null;
    /**
     * New value (JSON)
     */
    newValue?: string | null;
    /**
     * Source of the change (manual, import, merge, etc.)
     */
    source?: string | null;
}
export namespace DataProvenance {
}


