/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of documents
 */
export const DocumentType = {
    Unknown: 'Unknown',
    Photo: 'Photo',
    Document: 'Document',
    Certificate: 'Certificate',
    Letter: 'Letter',
    Video: 'Video',
    Audio: 'Audio',
    Other: 'Other'
} as const;
export type DocumentType = typeof DocumentType[keyof typeof DocumentType];

