/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivacyLevel } from './privacyLevel';
import { DocumentType } from './documentType';


/**
 * Document/file metadata
 */
export interface Document { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * User who owns this entity
     */
    userId?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    /**
     * Original filename
     */
    fileName?: string | null;
    /**
     * Display title
     */
    title?: string | null;
    /**
     * Document description
     */
    description?: string | null;
    /**
     * MIME type
     */
    contentType?: string | null;
    /**
     * File size in bytes
     */
    fileSizeBytes?: number;
    /**
     * S3/R2 object key
     */
    storageKey?: string | null;
    /**
     * S3/R2 bucket name
     */
    bucketName?: string | null;
    type?: DocumentType;
    /**
     * Optional date associated with document (photo date, document date, etc.)
     */
    documentDate?: string | null;
    /**
     * Tags for categorization
     */
    tags?: Array<string> | null;
    /**
     * MD5 hash for deduplication
     */
    contentHash?: string | null;
}
export namespace Document {
}


