/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of entities in the system
 */
export const EntityType = {
    Unknown: 'Unknown',
    Person: 'Person',
    Place: 'Place',
    Thing: 'Thing',
    Event: 'Event'
} as const;
export type EntityType = typeof EntityType[keyof typeof EntityType];

