/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of events
 */
export const EventType = {
    Unknown: 'Unknown',
    Birth: 'Birth',
    Death: 'Death',
    Marriage: 'Marriage',
    Divorce: 'Divorce',
    Move: 'Move',
    Education: 'Education',
    Employment: 'Employment',
    Purchase: 'Purchase',
    Sale: 'Sale',
    Accident: 'Accident',
    Achievement: 'Achievement',
    Meeting: 'Meeting',
    Trip: 'Trip',
    Memory: 'Memory',
    Other: 'Other'
} as const;
export type EventType = typeof EventType[keyof typeof EventType];

