/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Event summary (lightweight version)
 */
export interface EventSummaryDto { 
    eventId?: string;
    type?: string | null;
    description?: string | null;
    date?: string;
    placeId?: string | null;
    placeName?: string | null;
}

