/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { EventType } from './eventType';
import { PrivacyLevel } from './privacyLevel';


/**
 * DTO for event creation/update
 */
export interface EventDto { 
    id?: string | null;
    type?: EventType;
    title?: string | null;
    eventDate?: string;
    endDate?: string | null;
    description?: string | null;
    targetEntityType?: EntityType;
    targetEntityId?: string;
    placeId?: string | null;
    privacyLevel?: PrivacyLevel;
}
export namespace EventDto {
}


