/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { EventType } from './eventType';
import { PrivacyLevel } from './privacyLevel';


/**
 * Events for timeline functionality
 */
export interface Event { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * User who owns this entity
     */
    userId?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    type?: EventType;
    /**
     * Title/name of the event
     */
    title?: string | null;
    /**
     * When the event occurred
     */
    eventDate?: string;
    /**
     * End date for events with duration
     */
    endDate?: string | null;
    /**
     * Description of the event
     */
    description?: string | null;
    targetEntityType?: EntityType;
    /**
     * ID of the entity this event is about (person, place, or thing)
     */
    targetEntityId?: string;
    /**
     * Place where the event occurred
     */
    placeId?: string | null;
    /**
     * Flexible attributes stored as a map of key -> value
     */
    attributes?: { [key: string]: string; } | null;
}
export namespace Event {
}


