/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExportFormat } from './exportFormat';


/**
 * DTO for data export request
 */
export interface ExportRequestDto { 
    includePersons?: boolean;
    includePlaces?: boolean;
    includeThings?: boolean;
    includeEvents?: boolean;
    includeRelationships?: boolean;
    includeDocuments?: boolean;
    format?: ExportFormat;
}
export namespace ExportRequestDto {
}


