/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Export format
 */
export const ExportFormat = {
    Json: 'Json',
    Gedcom: 'Gedcom'
} as const;
export type ExportFormat = typeof ExportFormat[keyof typeof ExportFormat];

