/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Result of an import operation
 */
export interface ImportResult { 
    success?: boolean;
    errorMessage?: string | null;
    userId?: string;
    startedAt?: string;
    completedAt?: string | null;
    personsImported?: number;
    placesImported?: number;
    thingsImported?: number;
    eventsImported?: number;
    relationshipsImported?: number;
    documentsImported?: number;
    conflictsDetected?: number;
}

