/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';


/**
 * DTO for linking document to entity
 */
export interface LinkDocumentDto { 
    documentId?: string;
    entityId?: string;
    entityType?: EntityType;
    caption?: string | null;
    displayOrder?: number;
}
export namespace LinkDocumentDto {
}


