/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginFirebase400Response { 
    /**
     * Human readable id for this kind of error
     */
    slug?: string;
    /**
     * More info about the error, may sometimes be sufficient to display to user
     */
    message?: string;
}

