/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginFirebase500Response { 
    /**
     * Human readable id for this kind of error
     */
    slug?: string;
    /**
     * Unknown error occured
     */
    message?: string;
    /**
     * Id for the error report with this id
     */
    trace?: string;
}

