/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Single person creation data
 */
export interface PersonCreateDto { 
    name?: string | null;
    attributes?: { [key: string]: string; } | null;
}

