/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimelineEntry } from './timelineEntry';


/**
 * Person timeline view
 */
export interface PersonTimeline { 
    personId?: string;
    name?: string | null;
    timeline?: Array<TimelineEntry> | null;
}

