/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ThingSummaryDto } from './thingSummaryDto';
import { PlaceSummaryDto } from './placeSummaryDto';
import { RelationshipSummaryDto } from './relationshipSummaryDto';
import { EventSummaryDto } from './eventSummaryDto';


/**
 * Full person view with all related data
 */
export interface PersonFullView { 
    personId?: string;
    name?: string | null;
    attributes?: { [key: string]: string; } | null;
    relationships?: Array<RelationshipSummaryDto> | null;
    events?: Array<EventSummaryDto> | null;
    places?: Array<PlaceSummaryDto> | null;
    things?: Array<ThingSummaryDto> | null;
}

