/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for adding flexible attributes to a person
 */
export interface PersonAttributeDto { 
    personId?: string | null;
    category?: string | null;
    key?: string | null;
    value?: string | null;
}

