/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of places
 */
export const PlaceType = {
    Unknown: 'Unknown',
    Continent: 'Continent',
    Country: 'Country',
    State: 'State',
    County: 'County',
    City: 'City',
    Village: 'Village',
    District: 'District',
    Building: 'Building',
    Other: 'Other'
} as const;
export type PlaceType = typeof PlaceType[keyof typeof PlaceType];

