/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Flexible attributes for places (like PersonData)
 */
export interface PlaceData { 
    userId?: string;
    placeId?: string;
    /**
     * Category of this datapoint
     */
    category?: string | null;
    /**
     * Field name
     */
    key?: string | null;
    /**
     * The content of this datapoint
     */
    value?: string | null;
    /**
     * When this datapoint was last updated
     */
    changedAt?: string;
}

