/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for presigned URL response
 */
export interface PresignedUrlDto { 
    url?: string | null;
    expiresAt?: string;
    fileName?: string | null;
}

