/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Privacy levels for entities
 */
export const PrivacyLevel = {
    Private: 'Private',
    Family: 'Family',
    Friends: 'Friends',
    Public: 'Public'
} as const;
export type PrivacyLevel = typeof PrivacyLevel[keyof typeof PrivacyLevel];

