/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to record a conflict
 */
export interface RecordConflictRequest { 
    entityId?: string;
    fieldName?: string | null;
    value1?: string | null;
    value2?: string | null;
    citation1Id?: string | null;
    citation2Id?: string | null;
}

