/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Relationship suggestion
 */
export interface RelationshipSuggestion { 
    personId?: string;
    personName?: string | null;
    suggestedRelationType?: string | null;
    confidenceScore?: number;
    reason?: string | null;
    sharedEvents?: Array<string> | null;
    sharedPlaces?: Array<string> | null;
}

