/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';


/**
 * DTO for relationship creation/update
 */
export interface RelationshipDto { 
    id?: string | null;
    fromEntityType?: EntityType;
    fromEntityId?: string;
    toEntityType?: EntityType;
    toEntityId?: string;
    relationshipType?: string | null;
    language?: string | null;
    startDate?: string | null;
    endDate?: string | null;
    certainty?: number;
    source?: string | null;
    notes?: string | null;
}
export namespace RelationshipDto {
}


