/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Predefined relationship types with translations
 */
export interface RelationshipType { 
    type?: string | null;
    /**
     * Language code (de, en)
     */
    language?: string | null;
    /**
     * Translated name
     */
    displayName?: string | null;
    /**
     * Inverse relationship type (e.g., parent/child)
     */
    inverseType?: string | null;
    /**
     * Category (family, ownership, etc.)
     */
    category?: string | null;
}

