/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Relationship summary (lightweight version)
 */
export interface RelationshipSummaryDto { 
    relationshipId?: string;
    relatedPersonId?: string;
    relatedPersonName?: string | null;
    relationType?: string | null;
    startDate?: string | null;
    endDate?: string | null;
}

