/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictResolution } from './conflictResolution';


/**
 * DTO for conflict resolution
 */
export interface ResolveConflictDto { 
    conflictId?: string;
    entityId?: string;
    fieldName?: string | null;
    resolution?: ConflictResolution;
    resolvedValue?: string | null;
}
export namespace ResolveConflictDto {
}


