/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictResolutionStrategy } from './conflictResolutionStrategy';


/**
 * Request to resolve a conflict
 */
export interface ResolveConflictRequest { 
    entityId?: string;
    fieldName?: string | null;
    strategy?: ConflictResolutionStrategy;
    preferredValue?: string | null;
}
export namespace ResolveConflictRequest {
}


