/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConflictResolution } from './conflictResolution';


/**
 * DTO for responding to a share invitation
 */
export interface RespondToInvitationDto { 
    accept?: boolean;
    defaultConflictResolution?: ConflictResolution;
}
export namespace RespondToInvitationDto {
}


