/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ResultType = 'Unknown' | 'Person' | 'Location';

export const ResultType = {
    Unknown: 'Unknown' as ResultType,
    Person: 'Person' as ResultType,
    Location: 'Location' as ResultType
};

