/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResultType } from './resultType';


export interface SearchEntry { 
    userId?: string;
    keyWord?: string | null;
    type?: ResultType;
    fullId?: string | null;
    text?: string | null;
}
export namespace SearchEntry {
}


