/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchFacet } from './searchFacet';
import { SearchResult } from './searchResult';


/**
 * Paginated search result
 */
export interface SearchResultPage { 
    results?: Array<SearchResult> | null;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
    facets?: Array<SearchFacet> | null;
}

