/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Permission level for shared data
 */
export const SharePermission = {
    View: 'View',
    Edit: 'Edit',
    Admin: 'Admin'
} as const;
export type SharePermission = typeof SharePermission[keyof typeof SharePermission];

