/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Status of a share invitation
 */
export const ShareStatus = {
    Pending: 'Pending',
    Accepted: 'Accepted',
    Rejected: 'Rejected',
    Revoked: 'Revoked',
    Expired: 'Expired'
} as const;
export type ShareStatus = typeof ShareStatus[keyof typeof ShareStatus];

