/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { PrivacyLevel } from './privacyLevel';
import { ShareStatus } from './shareStatus';
import { SharePermission } from './sharePermission';


/**
 * Sharing invitation for data sharing between users
 */
export interface ShareInvitation { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * User who owns this entity
     */
    userId?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    /**
     * User who sent the invitation
     */
    fromUserId?: string;
    /**
     * User who receives the invitation
     */
    toUserId?: string;
    entityType?: EntityType;
    /**
     * ID of the entity being shared
     */
    entityId?: string;
    status?: ShareStatus;
    permission?: SharePermission;
    /**
     * Optional message from sender
     */
    message?: string | null;
    /**
     * When the invitation expires
     */
    expiresAt?: string | null;
    /**
     * When the invitation was accepted
     */
    acceptedAt?: string | null;
}
export namespace ShareInvitation {
}


