/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';
import { PrivacyLevel } from './privacyLevel';
import { SourceType } from './sourceType';


/**
 * Source citation for tracking information provenance
 */
export interface SourceCitation { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    /**
     * User who owns this citation (overrides base to add partition key)
     */
    userId?: string;
    /**
     * Entity this citation refers to
     */
    entityId?: string;
    entityType?: EntityType;
    /**
     * Field name being cited (e.g., \"birthDate\", \"name\")
     */
    fieldName?: string | null;
    sourceType?: SourceType;
    /**
     * Title of the source
     */
    title?: string | null;
    /**
     * Author of the source
     */
    author?: string | null;
    /**
     * Publisher
     */
    publisher?: string | null;
    /**
     * Publication date
     */
    publicationDate?: string | null;
    /**
     * URL or reference
     */
    url?: string | null;
    /**
     * Archive or repository name
     */
    repository?: string | null;
    /**
     * Call number or reference ID
     */
    callNumber?: string | null;
    /**
     * Specific page or location within source
     */
    page?: string | null;
    /**
     * Quality/reliability rating (0-100)
     */
    qualityRating?: number;
    /**
     * Notes about this citation
     */
    notes?: string | null;
    /**
     * Transcription or quote from source
     */
    transcription?: string | null;
    /**
     * Linked document ID (if digitized)
     */
    documentId?: string | null;
}
export namespace SourceCitation {
}


