/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of source document
 */
export const SourceType = {
    Unknown: 'Unknown',
    BirthCertificate: 'BirthCertificate',
    DeathCertificate: 'DeathCertificate',
    MarriageCertificate: 'MarriageCertificate',
    CensusRecord: 'CensusRecord',
    ChurchRecord: 'ChurchRecord',
    MilitaryRecord: 'MilitaryRecord',
    Immigration: 'Immigration',
    Newspaper: 'Newspaper',
    Book: 'Book',
    PersonalInterview: 'PersonalInterview',
    Letter: 'Letter',
    Diary: 'Diary',
    Photo: 'Photo',
    Video: 'Video',
    Audio: 'Audio',
    Website: 'Website',
    Other: 'Other'
} as const;
export type SourceType = typeof SourceType[keyof typeof SourceType];

