/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Storage quota tracking per user
 */
export interface StorageQuota { 
    userId?: string;
    /**
     * Total bytes used
     */
    usedBytes?: number;
    /**
     * Quota limit in bytes
     */
    quotaBytes?: number;
    /**
     * Number of documents
     */
    documentCount?: number;
    /**
     * Last updated timestamp
     */
    updatedAt?: string;
}

