/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivacyLevel } from './privacyLevel';
import { ThingType } from './thingType';


/**
 * Physical things/objects (cars, toys, buildings, etc.)
 */
export interface Thing { 
    /**
     * Unique identifier for this entity
     */
    id?: string;
    /**
     * User who owns this entity
     */
    userId?: string;
    /**
     * When this entity was created
     */
    createdAt?: string;
    /**
     * When this entity was last modified
     */
    updatedAt?: string;
    privacyLevel?: PrivacyLevel;
    /**
     * Name/identifier of the thing
     */
    name?: string | null;
    type?: ThingType;
    /**
     * Current owner (person ID)
     */
    ownerId?: string | null;
    /**
     * Manufacturer or creator
     */
    manufacturer?: string | null;
    /**
     * Year of manufacture/creation
     */
    yearMade?: number | null;
    /**
     * Model or type designation
     */
    model?: string | null;
    /**
     * Serial number or registration
     */
    serialNumber?: string | null;
    /**
     * Flexible attributes stored as a map of key -> value
     */
    attributes?: { [key: string]: string; } | null;
}
export namespace Thing {
}


