/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Types of things
 */
export const ThingType = {
    Unknown: 'Unknown',
    Vehicle: 'Vehicle',
    Building: 'Building',
    Toy: 'Toy',
    Tool: 'Tool',
    Furniture: 'Furniture',
    Jewelry: 'Jewelry',
    Document: 'Document',
    Book: 'Book',
    Artwork: 'Artwork',
    Clothing: 'Clothing',
    Other: 'Other'
} as const;
export type ThingType = typeof ThingType[keyof typeof ThingType];

