/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Thing summary (lightweight version)
 */
export interface ThingSummaryDto { 
    thingId?: string;
    name?: string | null;
    type?: string | null;
    description?: string | null;
}

