/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivacyLevel } from './privacyLevel';
import { ThingType } from './thingType';


/**
 * DTO for thing creation/update
 */
export interface ThingDto { 
    id?: string | null;
    name?: string | null;
    type?: ThingType;
    ownerId?: string | null;
    manufacturer?: string | null;
    yearMade?: number | null;
    model?: string | null;
    serialNumber?: string | null;
    privacyLevel?: PrivacyLevel;
}
export namespace ThingDto {
}


