/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Timeline entry for person
 */
export interface TimelineEntry { 
    date?: string;
    type?: string | null;
    title?: string | null;
    description?: string | null;
    relatedEntityId?: string | null;
    location?: string | null;
}

