/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityType } from './entityType';


/**
 * DTO for timeline requests
 */
export interface TimelineRequestDto { 
    entityType?: EntityType;
    entityId?: string;
    startDate?: string | null;
    endDate?: string | null;
}
export namespace TimelineRequestDto {
}


