/**
 * con-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentType } from './documentType';


/**
 * DTO for document upload
 */
export interface UploadDocumentDto { 
    fileName?: string | null;
    storageKey?: string | null;
    fileSizeBytes?: number;
    title?: string | null;
    description?: string | null;
    type?: DocumentType;
    documentDate?: string | null;
    tags?: Array<string> | null;
}
export namespace UploadDocumentDto {
}


